spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eriks_db
    username: admin
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/8fdffe13-76f6-4e29-ac3e-afcd264ca6cc/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/8fdffe13-76f6-4e29-ac3e-afcd264ca6cc/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            tenant-id: 8fdffe13-76f6-4e29-ac3e-afcd264ca6cc
            client-id: 1608df86-1dc2-466c-a424-771c853c2abe
            client-secret: .GJQ__9b8e5gx_ZlD-ILAKY1pT_60Ct58_
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/api/login/oauth2/code/azure'
            scope: openid
  liquibase:
    change-log: classpath:/db/changelog-master.xml

server:
  servlet:
    context-path: /api
  forward-headers-strategy: native
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

activemq:
  broker-url: tcp://localhost:61616

  springdoc:
    api-docs:
      path: /api-docs
disable:
  csrf: ${DISABLE_CSRF:true}
